version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '09:58'
    open-pull-requests-limit: 10
